SELECT DISTINCT *
FROM
  (SELECT O.CODCOLIGADA,
          O.CODCCUSTO OS,
          O.CODORDEM OP,
          KA.CODATIVIDADE,
          KA.DSCATIVIDADE,
          N.DESCRICAO ITEM,
          N.MATERIAL,
          KC.NUMEXEC EXECUCAO,
          N.POSICAODESENHO POSICAO,
          N.BITOLA,
          A.IDATVORDEM,
          A.CODESTRUTURA,
          N.NUMDESENHO,
          A.QTPREVISTA QTDEPLANEJADA,
          FTAG.TAG,
          COALESCE(
                     (SELECT A.QTPREVISTA -
                        (SELECT SUM(ISNULL(Z1.QUANTIDADE, Z2.QUANTIDADE)) QUANTIDADE
                         FROM KATVORDEM ZA
                         LEFT JOIN FLUIG.DBO.Z_DELP_NECESSIDADEPAPC Z1 ON ZA.CODCOLIGADA=Z1.CODCOLIGADA
                         AND ZA.CODFILIAL=Z1.CODFILIAL
                         AND ZA.CODORDEM=Z1.CODORDEM
                         AND ZA.CODATIVIDADE=Z1.CODATIVIDADE
                         LEFT JOIN ZMDPLANOAPROVEITAMENTOCORTE Z2 ON Z2.CODCOLIGADA=ZA.CODCOLIGADA
                         AND Z2.CODFILIAL=ZA.CODFILIAL
                         AND Z2.CODORDEM=ZA.CODORDEM
                         AND Z2.CODATIVIDADE=ZA.CODATIVIDADE
                         WHERE ZA.CODORDEM=O.CODORDEM
                           AND ZA.CODATIVIDADE=A.CODATIVIDADE
                           AND ZA.CODCOLIGADA=O.CODCOLIGADA
                           AND ZA.CODFILIAL=O.CODFILIAL ) QTDE),A.QTPREVISTA-ISNULL(A.QUANTIDADE, 0)) SALDO
   FROM KORDEM O
   INNER JOIN KORDEMCOMPL KC ON O.CODCOLIGADA = KC.CODCOLIGADA
   AND O.CODFILIAL = KC.CODFILIAL
   AND O.CODORDEM = KC.CODORDEM
   INNER JOIN KATVORDEM A ON A.CODCOLIGADA = O.CODCOLIGADA
   AND A.CODFILIAL = O.CODFILIAL
   AND A.CODORDEM = O.CODORDEM
   INNER JOIN KATIVIDADE KA ON A.CODCOLIGADA = KA.CODCOLIGADA
   AND A.CODFILIAL = KA.CODFILIAL
   AND A.CODATIVIDADE = KA.CODATIVIDADE
   INNER JOIN KATVORDEMMP KMP ON KMP.CODCOLIGADA=A.CODCOLIGADA
   AND KMP.CODFILIAL=A.CODFILIAL
   AND KMP.CODORDEM=A.CODORDEM
   AND KMP.IDATIVIDADE=A.IDATVORDEM
   AND KMP.EFETIVADO=0
   INNER JOIN FLUIG.DBO.Z_CRM_EX001005 N ON N.OS = O.CODCCUSTO COLLATE LATIN1_GENERAL_CI_AS
   AND N.CODIGOPRD = A.CODESTRUTURA COLLATE LATIN1_GENERAL_CI_AS
   AND N.EXECUCAO = KC.NUMEXEC
   AND N.ITEMEXCLUSIVO <> 2
   INNER JOIN FLUIG.DBO.Z_CRM_EX001005COMPL FTAG ON FTAG.CODCOLIGADA=O.CODCOLIGADA
   AND FTAG.CODFILIAL=O.CODFILIAL
   AND FTAG.OS=N.OS
   AND FTAG.EXECUCAO=N.EXECUCAO
   AND FTAG.IDCRIACAO=N.IDCRIACAO
   WHERE O.CODCOLIGADA=1
     AND O.CODFILIAL='7'
     AND O.CODCCUSTO='3.07867.32.001'
     AND O.CODCCUSTO IS NOT NULL
     AND (KA.DSCATIVIDADE LIKE '%CORTAR MANUAL%'
          OR KA.DSCATIVIDADE LIKE '%SERRAR%'
          OR KA.DSCATIVIDADE LIKE '%CORTAR%'
          OR KA.DSCATIVIDADE LIKE '%TRAÃ‡AR%'
          OR KA.DSCATIVIDADE LIKE '%CHANFRAR%'
          OR KA.DSCATIVIDADE LIKE '%DOBRAR%'
          OR KA.DSCATIVIDADE LIKE '%MONTAR%') ) R where op = '72285/23'