DECLARE @Os NVARCHAR(50) = '3.07843.32.001'
DECLARE @atividade nvarchar(50) = 'WATV006-03'
DECLARE @desenho nvarchar(50) = 'DU700265724'
DECLARE @ordem nvarchar(50) = '37347/22'
DECLARE @plano nvarchar(50) = 'CNC003796'
DECLARE @resultado VARCHAR(MAX);

SET @resultado = '';

SELECT DISTINCT
    Z.FORNPARA,
    E.NUMDESENHO,
    E.SEQUENCIA,
    E.ORDEM,
    E.QUANTIDADE,
    E.DESCRICAO,
    E.DIMENSOES,
    E.OS,
    E.PLANOCORTE,
    E.POSICAO,
    E.ATIVIDADE,
    (
        SELECT STUFF((
                SELECT '/' + Z2.DESCATIVIDADE
                FROM Z_CRM_EX001021 AS Z2
                INNER JOIN CORPORE_DEV.dbo.ESTOQUECD AS E2 ON Z2.OSPROCESSO = E2.OS COLLATE SQL_Latin1_General_CP1_CI_AI
                INNER JOIN Z_CRM_EX001005 AS ZZ2 ON ZZ2.OS = Z2.OSPROCESSO AND ZZ2.IDCRIACAO = Z2.IDCRIACAOPROCESSO
                INNER JOIN Z_CRM_EX001005COMPL AS ZCM2 ON ZCM2.OS = ZZ2.OS AND ZCM2.CODFILIAL = ZZ2.CODFILIAL 
                    AND ZCM2.CODCOLIGADA = ZZ2.CODCOLIGADA AND Z2.EXECUCAO = ZCM2.EXECUCAO AND ZZ2.EXECUCAO = ZCM2.EXECUCAO 
                    AND ZCM2.IDCRIACAO = Z2.IDCRIACAOPROCESSO AND ZCM2.CODORDEM = E2.ORDEM COLLATE SQL_Latin1_General_CP1_CI_AI
                INNER JOIN CORPORE_DEV.dbo.KATIVIDADE AS KAT2 ON KAT2.CODATIVIDADE = E2.ATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI 
                    AND KAT2.CODCOLIGADA = ZZ2.CODCOLIGADA AND KAT2.CODFILIAL = ZZ2.CODFILIAL
                WHERE Z2.OSPROCESSO = @Os
                    AND ZZ2.NUMDESENHO = E.NUMDESENHO
                    AND ZCM2.CODORDEM = E.ORDEM COLLATE SQL_Latin1_General_CP1_CI_AI
                FOR XML PATH('')), 1, 1, '')
    ) AS DESCATIVIDADES,
    E.NOMEENTREGUE,
    E.NOMERETIRADA,
    E.DATAENTREGUE,
    E.DATARETIRADA 
FROM
    ESTOQUECD E
    INNER JOIN Z_CRM_EX001005COMPL ZL ON E.ORDEM = ZL.CODORDEM COLLATE SQL_Latin1_General_CP1_CI_AI
    INNER JOIN Z_CRM_EX001021 Z ON Z.IDCRIACAOPROCESSO = ZL.IDCRIACAO AND Z.EXECUCAO = ZL.EXECUCAO AND Z.OSPROCESSO = ZL.OS
WHERE
    E.OS = @Os
    AND E.PLANOCORTE = @plano
ORDER BY
    E.ORDEM,
    Z.PRIORIDADE ASC;
